### ISSUE TITLE
Abnormal process termination

### ISSUE THREAD

**Issue by ghost** [tmthrgd/tmpfile#1]
Hi,

Thanks for the simple and useful library.

I am going to implement Java version of your tmpfile.

`path := "/proc/self/fd/" + strconv.FormatUint(uint64(fd), 10)`

I did not understand the above line, could you please let me know why did you use the /proc/self/fd path.

My second question is, what will happen if process terminated abnormally?

Thanks

**Comment by tmthrgd** [comment]
The `/proc/self/fd/...` path is given in the [man page for open(2)](http://man7.org/linux/man-pages/man2/open.2.html):
> O_TMPFILE must be specified with one of O_RDWR or O_WRONLY and, optionally, O_EXCL.  If O_EXCL is not specified, then linkat(2) can be used to link the temporary file into the filesystem, making it permanent, using code like the following:
>
>     char path[PATH_MAX];
>     fd = open("/path/to/dir", O_TMPFILE | O_RDWR,
>                             S_IRUSR | S_IWUSR);
>
>     /* File I/O on 'fd'... */
>
>     snprintf(path, PATH_MAX,  "/proc/self/fd/%d", fd);
>     linkat(AT_FDCWD, path, AT_FDCWD, "/path/for/file",
>                             AT_SYMLINK_FOLLOW);

This is used because the file isn't actually linked into the filesystem anywhere and thus doesn't have a path, but it *can* be accessed by it's file descriptor. `/proc/self` refers to the currently executing program, and `/proc/self/fd` refers to it's open file descriptors. So the line you quote above, simply produces the required filesystem path (without depending on the [fmt pacakge](https://golang.org/pkg/fmt/)), and is equivalent to the `snprintf` line in the example above.

I can only quote the man page and speculate as to what would happen under abnormal termination. According to the [man page](http://man7.org/linux/man-pages/man2/open.2.html) [emphasis mine]:
> [...] Anything written to the resulting file will be **lost when the last file descriptor is closed**, unless the file is given a name.
>
> [...]
>
> There are two main use cases for O_TMPFILE:
> *  Improved tmpfile(3) functionality: race-free creation of temporary files that (1) are **automatically deleted when closed**; (2) can never be reached via any pathname; (3) are not subject to symlink attacks; and (4) do not require the caller to devise unique names.
>
> [...]

If the process was to terminate as a result of a signal, the kernel *should* still delete the file (unless it was linked into the filesystem). I would wager that the file will be automatically deleted with anything short of a kernel panic.

I hope I've given you satisfactory answers, and I'm glad this package was useful for you.

**Comment by ghost** [comment]
Thanks for the detailed information.
Now it more clear for me to implement Java version.
